{
  "Selected": "Selected",
  "Space": "Space",
  "User Name": "User Name",
  "Summary": "Summary",
  "Created": "Created",
  "Shifts": "Shifts",
  "My Shifts": "My Shifts",
  "Following": "Following",
  "Settings": "Settings",
  "Login": "Login",
  "Welcome": "Welcome",
  "Plugins": "Plugins",
  "Installed": "Installed",
  "Account": "Account",
  "Highlights": "Highlights",
  "ImageSwap": "ImageSwap",
  "SourceShift": "SourceShift",
  "Notes": "Notes"
}