{
  "Selected": "선택",
  "Space": "우주",
  "User Name": "사용자 이름을",
  "Summary": "요약",
  "Created": "작성일",
  "Shifts": "교대",
  "My Shifts": "내 교대",
  "Following": "다음",
  "Settings": "설정을",
  "Login": "로그인",
  "Welcome": "환영",
  "Plugins": "플러그인",
  "Installed": "설치",
  "Account": "계정",
  "Highlights": "하이라이트",
  "ImageSwap": "이미지를 스왑",
  "SourceShift": "HTML 전환",
  "Notes": "노트"
}